name: Release & Publish Extension

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0

      - name: Install dependencies
        run: npm ci

      # 🧭 1. Semantic Release — versiyon bump + changelog + tag
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # 🚀 2. VS Code Marketplace'e publish et
      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p $MARKET_TOKEN
        env:
          MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}