name: version

on:
    push:
        branches:
            - main

jobs:
    bump-version:
        runs-on: ubuntu-latest

        permissions:
            contents: write # commit/tag için gerekli

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0 # tag'ların da gelmesi için ÖNEMLİ

            - name: Setup Git identity
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Bump version, commit and push tag
              run: |
                  VERSION=$(npm version patch -m "chore: bump version to %s [skip ci]")
                  echo "📦 Version bumped to $VERSION"

                  # push commit ve tag
                  git push origin HEAD:main
                  git push origin --tags
